Disable ListTypeSelector animations under tests
This was causing:
> androidx.compose.ui.test.junit4.android.ComposeNotIdleException: Idling resource timed out: possibly due to compose being busy.